### ISSUE TITLE
ImportError: cannot import name 'default_revision_manager'

### ISSUE THREAD

**Issue by nibytes** [aldryn/aldryn-newsblog#456]
```
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x04127C00>
Traceback (most recent call last):
  File "C:\Users\ntsfk\OneDrive\Documents\Work\p35d18\lib\site-packages\django\utils\autoreload.py", line 229, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\ntsfk\OneDrive\Documents\Work\p35d18\lib\site-packages\django\core\management\commands\runserver.py", line 107, in inner_run
    autoreload.raise_last_exception()
  File "C:\Users\ntsfk\OneDrive\Documents\Work\p35d18\lib\site-packages\django\utils\autoreload.py", line 252, in raise_last_exception
    six.reraise(*_exception)
  File "C:\Users\ntsfk\OneDrive\Documents\Work\p35d18\lib\site-packages\django\utils\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\ntsfk\OneDrive\Documents\Work\p35d18\lib\site-packages\django\utils\autoreload.py", line 229, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\ntsfk\OneDrive\Documents\Work\p35d18\lib\site-packages\django\__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\ntsfk\OneDrive\Documents\Work\p35d18\lib\site-packages\django\apps\registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "C:\Users\ntsfk\OneDrive\Documents\Work\p35d18\lib\site-packages\django\apps\config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Users\ntsfk\OneDrive\Documents\Work\p35d18\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\ntsfk\OneDrive\Documents\Work\p35d18\lib\site-packages\aldryn_newsblog\models.py", line 24, in <module>
    from aldryn_people.models import Person
  File "C:\Users\ntsfk\OneDrive\Documents\Work\p35d18\lib\site-packages\aldryn_people\models.py", line 15, in <module>
    from reversion.revisions import (
ImportError: cannot import name 'default_revision_manager'

```
requirements.txt
`aldryn-apphooks-config==0.3.3
aldryn-boilerplates==0.7.5
aldryn-categories==1.0.4
aldryn-common==1.0.4
aldryn-newsblog==1.3.3
aldryn-people==1.2.2
aldryn-reversion==1.1.0
aldryn-translation-tools==0.2.1
appdirs==1.4.3
Babel==2.4.0
backport-collections==0.1
cmsplugin-filer==1.1.3
dj-database-url==0.4.2
Django==1.8.17
django-admin-sortable==1.6.7
django-appconf==1.0.2
django-appdata==0.1.6
django-classy-tags==0.8.0
django-cms==3.4.2
django-filer==1.2.7
django-formtools==2.0
django-ipware==1.1.6
django-mptt==0.8.7
django-parler==1.7
django-phonenumber-field==1.3.0
django-polymorphic==1.0.2
django-reversion==2.0.8
django-sekizai==0.10.0
django-sortedm2m==1.3.3
django-taggit==0.22.1
django-treebeard==4.1.0
djangocms-admin-style==1.2.6.2
djangocms-attributes-field==0.2.0
djangocms-column==1.7.0
djangocms-forms==0.2.5
djangocms-googlemap==1.0.2
djangocms-installer==0.9.5
djangocms-link==2.1.1
djangocms-picture==2.0.4
djangocms-slider==0.2.4
djangocms-snippet==1.9.2
djangocms-style==2.0.1
djangocms-teaser==0.2.0
djangocms-text-ckeditor==3.4.0
djangocms-video==2.0.3
easy-thumbnails==2.0.1
hashids==1.2.0
html5lib==0.9999999
jsonfield==2.0.1
olefile==0.44
packaging==16.8
phonenumbers==8.5.0
phonenumberslite==8.5.0
Pillow==4.0.0
psycopg2==2.7.1
pyparsing==2.2.0
python-dateutil==2.6.0
python-slugify==1.2.0
pytz==2016.10
requests==2.14.2
six==1.10.0
sorl-thumbnail==12.3
tablib==0.11.4
tzlocal==1.3
Unidecode==0.4.20
virtualenv==15.1.0
YURL==0.13
`
Python 3.5.2
Django 1.8.17
DjangoCMS 3.4.2

**Comment by krzysztofp** [comment]
Same issue here:

aldryn-apphooks-config==0.3.3
aldryn-boilerplates==0.7.5
aldryn-categories==1.0.4
aldryn-common==1.0.4
aldryn-newsblog==1.3.3
aldryn-people==1.2.2
aldryn-reversion==1.1.0
aldryn-translation-tools==0.2.1
Babel==2.4.0
backport-collections==0.1
cmsplugin-filer==1.1.3
dj-database-url==0.4.2
Django==1.8.18
django-appconf==1.0.2
django-appdata==0.1.6
django-classy-tags==0.8.0
django-cms==3.4.4
django-filer==1.2.7
django-formtools==2.0
django-mptt==0.8.7
django-parler==1.8
django-phonenumber-field==1.3.0
django-polymorphic==1.0.2
django-reversion==2.0.9
django-sekizai==0.10.0
django-sortedm2m==1.5.0
django-taggit==0.22.1
django-treebeard==4.1.2
djangocms-admin-style==1.2.7
djangocms-attributes-field==0.3.0
djangocms-column==1.7.0
djangocms-googlemap==1.1.1
djangocms-installer==0.9.6
djangocms-link==2.1.2
djangocms-snippet==1.9.2
djangocms-style==2.0.2
djangocms-text-ckeditor==3.5.0
djangocms-video==2.0.3
easy-thumbnails==2.4.1
html5lib==0.9999999
lxml==3.8.0
olefile==0.44
phonenumbers==8.7.1
phonenumberslite==8.7.1
Pillow==4.2.1
psycopg2==2.7.1
python-dateutil==2.6.1
python-slugify==1.2.0
pytz==2017.2
reversion==0.2
six==1.10.0
toml==0.9.2
tzlocal==1.4
Unidecode==0.4.21
YURL==0.13
